/*
  Esquema base adaptado del Script Database.txt entregado para PAQTERIA.
  Este archivo se ejecuta solo para crear Paqteria desde cero. No borra datos.
  Se quitaron los usuarios SQL paqteria_user/paqteria_app: la aplicación usa
  autenticación integrada de Windows, configurada en sqlserver-windows-access.sql.
*/
GO

USE [master]
GO
/****** Objeto: Database [Paqteria] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
CREATE DATABASE [Paqteria]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Paqteria', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLSERVERPAQUETE\MSSQL\DATA\Paqteria.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Paqteria_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLSERVERPAQUETE\MSSQL\DATA\Paqteria_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Paqteria] SET COMPATIBILITY_LEVEL = 170
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Paqteria].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Paqteria] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Paqteria] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Paqteria] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Paqteria] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Paqteria] SET ARITHABORT OFF 
GO
ALTER DATABASE [Paqteria] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Paqteria] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Paqteria] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Paqteria] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Paqteria] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Paqteria] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Paqteria] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Paqteria] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Paqteria] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Paqteria] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Paqteria] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Paqteria] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Paqteria] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Paqteria] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Paqteria] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Paqteria] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Paqteria] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Paqteria] SET RECOVERY FULL 
GO
ALTER DATABASE [Paqteria] SET  MULTI_USER 
GO
ALTER DATABASE [Paqteria] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Paqteria] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Paqteria] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Paqteria] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Paqteria] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Paqteria] SET OPTIMIZED_LOCKING = OFF 
GO
ALTER DATABASE [Paqteria] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [Paqteria] SET QUERY_STORE = ON
GO
ALTER DATABASE [Paqteria] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [Paqteria]
GO
/****** Objeto: Table [dbo].[CENTROS_DISTRIBUCION] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CENTROS_DISTRIBUCION](
	[id_centro] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](150) NOT NULL,
	[ciudad] [varchar](100) NOT NULL,
	[direccion] [varchar](255) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_centro] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[COMPROBANTES_ENTREGA] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COMPROBANTES_ENTREGA](
	[id_comprobante] [int] IDENTITY(1,1) NOT NULL,
	[id_paquete] [int] NOT NULL,
	[id_repartidor] [int] NOT NULL,
	[nombre_receptor] [varchar](150) NOT NULL,
	[url_foto_evidencia] [varchar](500) NULL,
	[url_firma_receptor] [varchar](500) NULL,
	[fecha_hora] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_comprobante] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[HISTORIAL_SEGUIMIENTO] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HISTORIAL_SEGUIMIENTO](
	[id_historial] [int] IDENTITY(1,1) NOT NULL,
	[id_paquete] [int] NOT NULL,
	[titulo] [varchar](150) NOT NULL,
	[descripcion] [text] NULL,
	[fecha_hora] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_historial] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[INCIDENCIAS_ENTREGA] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INCIDENCIAS_ENTREGA](
	[id_incidencia] [int] IDENTITY(1,1) NOT NULL,
	[id_paquete] [int] NOT NULL,
	[id_repartidor] [int] NOT NULL,
	[tipo_incidencia] [varchar](100) NOT NULL,
	[comentario] [text] NULL,
	[url_foto_reporte] [varchar](500) NULL,
	[fecha_hora] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_incidencia] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[PAQUETES] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PAQUETES](
	[id_paquete] [int] IDENTITY(1,1) NOT NULL,
	[folio] [varchar](50) NOT NULL,
	[id_cliente] [int] NOT NULL,
	[id_centro_origen] [int] NOT NULL,
	[direccion_origen] [varchar](255) NOT NULL,
	[direccion_destino] [varchar](255) NOT NULL,
	[coordenadas_destino] [varchar](100) NULL,
	[peso_kg] [decimal](10, 2) NOT NULL,
	[tamano_etiqueta] [varchar](50) NULL,
	[es_prioritario] [bit] NULL,
	[es_fragil] [bit] NULL,
	[estado_actual] [varchar](50) NOT NULL,
	[fecha_creacion] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_paquete] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[folio] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[PARADAS_RUTA] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PARADAS_RUTA](
	[id_parada] [int] IDENTITY(1,1) NOT NULL,
	[id_turno] [int] NOT NULL,
	[id_paquete] [int] NOT NULL,
	[orden_secuencia] [int] NOT NULL,
	[estado_parada] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_parada] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[ROLES] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROLES](
	[id_rol] [int] IDENTITY(1,1) NOT NULL,
	[nombre] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_rol] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TICKETS_SOPORTE] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TICKETS_SOPORTE](
	[id_ticket] [int] IDENTITY(1,1) NOT NULL,
	[id_cliente] [int] NOT NULL,
	[id_paquete] [int] NOT NULL,
	[motivo] [varchar](150) NOT NULL,
	[descripcion] [text] NULL,
	[estado] [varchar](50) NOT NULL,
	[fecha_creacion] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_ticket] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[TURNOS_REPARTIDOR] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TURNOS_REPARTIDOR](
	[id_turno] [int] IDENTITY(1,1) NOT NULL,
	[id_repartidor] [int] NOT NULL,
	[id_unidad] [int] NOT NULL,
	[fecha_turno] [date] NOT NULL,
	[estado_turno] [varchar](50) NOT NULL,
	[total_paquetes] [int] NULL,
	[tiempo_estimado_horas] [decimal](5, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_turno] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[UNIDADES] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UNIDADES](
	[id_unidad] [int] IDENTITY(1,1) NOT NULL,
	[id_centro] [int] NOT NULL,
	[codigo_unidad] [varchar](50) NOT NULL,
	[placas] [varchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id_unidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[codigo_unidad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Objeto: Table [dbo].[USUARIOS] Fecha de script: 06/10/2026 12:14:06 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[USUARIOS](
	[id_usuario] [int] IDENTITY(1,1) NOT NULL,
	[id_rol] [int] NOT NULL,
	[nombre] [varchar](150) NOT NULL,
	[email] [varchar](150) NOT NULL,
	[telefono] [varchar](20) NULL,
	[password_hash] [varchar](255) NOT NULL,
	[fecha_registro] [datetime2](7) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPROBANTES_ENTREGA] ADD  DEFAULT (getdate()) FOR [fecha_hora]
GO
ALTER TABLE [dbo].[HISTORIAL_SEGUIMIENTO] ADD  DEFAULT (getdate()) FOR [fecha_hora]
GO
ALTER TABLE [dbo].[INCIDENCIAS_ENTREGA] ADD  DEFAULT (getdate()) FOR [fecha_hora]
GO
ALTER TABLE [dbo].[PAQUETES] ADD  DEFAULT ((0)) FOR [es_prioritario]
GO
ALTER TABLE [dbo].[PAQUETES] ADD  DEFAULT ((0)) FOR [es_fragil]
GO
ALTER TABLE [dbo].[PAQUETES] ADD  DEFAULT (getdate()) FOR [fecha_creacion]
GO
ALTER TABLE [dbo].[TICKETS_SOPORTE] ADD  DEFAULT (getdate()) FOR [fecha_creacion]
GO
ALTER TABLE [dbo].[TURNOS_REPARTIDOR] ADD  DEFAULT ((0)) FOR [total_paquetes]
GO
ALTER TABLE [dbo].[USUARIOS] ADD  DEFAULT (getdate()) FOR [fecha_registro]
GO
ALTER TABLE [dbo].[COMPROBANTES_ENTREGA]  WITH CHECK ADD  CONSTRAINT [FK_COMPROBANTES_PAQUETES] FOREIGN KEY([id_paquete])
REFERENCES [dbo].[PAQUETES] ([id_paquete])
GO
ALTER TABLE [dbo].[COMPROBANTES_ENTREGA] CHECK CONSTRAINT [FK_COMPROBANTES_PAQUETES]
GO
ALTER TABLE [dbo].[COMPROBANTES_ENTREGA]  WITH CHECK ADD  CONSTRAINT [FK_COMPROBANTES_REPARTIDOR] FOREIGN KEY([id_repartidor])
REFERENCES [dbo].[USUARIOS] ([id_usuario])
GO
ALTER TABLE [dbo].[COMPROBANTES_ENTREGA] CHECK CONSTRAINT [FK_COMPROBANTES_REPARTIDOR]
GO
ALTER TABLE [dbo].[HISTORIAL_SEGUIMIENTO]  WITH CHECK ADD  CONSTRAINT [FK_HISTORIAL_PAQUETES] FOREIGN KEY([id_paquete])
REFERENCES [dbo].[PAQUETES] ([id_paquete])
GO
ALTER TABLE [dbo].[HISTORIAL_SEGUIMIENTO] CHECK CONSTRAINT [FK_HISTORIAL_PAQUETES]
GO
ALTER TABLE [dbo].[INCIDENCIAS_ENTREGA]  WITH CHECK ADD  CONSTRAINT [FK_INCIDENCIAS_PAQUETES] FOREIGN KEY([id_paquete])
REFERENCES [dbo].[PAQUETES] ([id_paquete])
GO
ALTER TABLE [dbo].[INCIDENCIAS_ENTREGA] CHECK CONSTRAINT [FK_INCIDENCIAS_PAQUETES]
GO
ALTER TABLE [dbo].[INCIDENCIAS_ENTREGA]  WITH CHECK ADD  CONSTRAINT [FK_INCIDENCIAS_REPARTIDOR] FOREIGN KEY([id_repartidor])
REFERENCES [dbo].[USUARIOS] ([id_usuario])
GO
ALTER TABLE [dbo].[INCIDENCIAS_ENTREGA] CHECK CONSTRAINT [FK_INCIDENCIAS_REPARTIDOR]
GO
ALTER TABLE [dbo].[PAQUETES]  WITH CHECK ADD  CONSTRAINT [FK_PAQUETES_CENTRO_ORIGEN] FOREIGN KEY([id_centro_origen])
REFERENCES [dbo].[CENTROS_DISTRIBUCION] ([id_centro])
GO
ALTER TABLE [dbo].[PAQUETES] CHECK CONSTRAINT [FK_PAQUETES_CENTRO_ORIGEN]
GO
ALTER TABLE [dbo].[PAQUETES]  WITH CHECK ADD  CONSTRAINT [FK_PAQUETES_CLIENTE] FOREIGN KEY([id_cliente])
REFERENCES [dbo].[USUARIOS] ([id_usuario])
GO
ALTER TABLE [dbo].[PAQUETES] CHECK CONSTRAINT [FK_PAQUETES_CLIENTE]
GO
ALTER TABLE [dbo].[PARADAS_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_PARADAS_PAQUETES] FOREIGN KEY([id_paquete])
REFERENCES [dbo].[PAQUETES] ([id_paquete])
GO
ALTER TABLE [dbo].[PARADAS_RUTA] CHECK CONSTRAINT [FK_PARADAS_PAQUETES]
GO
ALTER TABLE [dbo].[PARADAS_RUTA]  WITH CHECK ADD  CONSTRAINT [FK_PARADAS_TURNOS] FOREIGN KEY([id_turno])
REFERENCES [dbo].[TURNOS_REPARTIDOR] ([id_turno])
GO
ALTER TABLE [dbo].[PARADAS_RUTA] CHECK CONSTRAINT [FK_PARADAS_TURNOS]
GO
ALTER TABLE [dbo].[TICKETS_SOPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TICKETS_CLIENTE] FOREIGN KEY([id_cliente])
REFERENCES [dbo].[USUARIOS] ([id_usuario])
GO
ALTER TABLE [dbo].[TICKETS_SOPORTE] CHECK CONSTRAINT [FK_TICKETS_CLIENTE]
GO
ALTER TABLE [dbo].[TICKETS_SOPORTE]  WITH CHECK ADD  CONSTRAINT [FK_TICKETS_PAQUETES] FOREIGN KEY([id_paquete])
REFERENCES [dbo].[PAQUETES] ([id_paquete])
GO
ALTER TABLE [dbo].[TICKETS_SOPORTE] CHECK CONSTRAINT [FK_TICKETS_PAQUETES]
GO
ALTER TABLE [dbo].[TURNOS_REPARTIDOR]  WITH CHECK ADD  CONSTRAINT [FK_TURNOS_REPARTIDOR] FOREIGN KEY([id_repartidor])
REFERENCES [dbo].[USUARIOS] ([id_usuario])
GO
ALTER TABLE [dbo].[TURNOS_REPARTIDOR] CHECK CONSTRAINT [FK_TURNOS_REPARTIDOR]
GO
ALTER TABLE [dbo].[TURNOS_REPARTIDOR]  WITH CHECK ADD  CONSTRAINT [FK_TURNOS_UNIDADES] FOREIGN KEY([id_unidad])
REFERENCES [dbo].[UNIDADES] ([id_unidad])
GO
ALTER TABLE [dbo].[TURNOS_REPARTIDOR] CHECK CONSTRAINT [FK_TURNOS_UNIDADES]
GO
ALTER TABLE [dbo].[UNIDADES]  WITH CHECK ADD  CONSTRAINT [FK_UNIDADES_CENTROS] FOREIGN KEY([id_centro])
REFERENCES [dbo].[CENTROS_DISTRIBUCION] ([id_centro])
GO
ALTER TABLE [dbo].[UNIDADES] CHECK CONSTRAINT [FK_UNIDADES_CENTROS]
GO
ALTER TABLE [dbo].[USUARIOS]  WITH CHECK ADD  CONSTRAINT [FK_USUARIOS_ROLES] FOREIGN KEY([id_rol])
REFERENCES [dbo].[ROLES] ([id_rol])
GO
ALTER TABLE [dbo].[USUARIOS] CHECK CONSTRAINT [FK_USUARIOS_ROLES]
GO
USE [master]
GO
ALTER DATABASE [Paqteria] SET  READ_WRITE 
GO
